#!/bin/sh

set -e

OUTPUT="${OUTPUT:-target}"
BUILD_TYPE="${BUILD_TYPE:-Release}"

# cd to /$OUTPUT, creating it if it doesn't exist.
cd "$(dirname "$0")"
mkdir -p "$OUTPUT"
cd "$OUTPUT"

echo "CMake:"
echo "Output directory: $OUTPUT"
echo "Build type: $BUILD_TYPE"
cmake .. -DCMAKE_BUILD_TYPE="$BUILD_TYPE"

echo
echo "Make:"
make -k
