#!/bin/sh

set -e

BUILD_TYPE="${BUILD_TYPE:-Release}"
OUTPUT="${OUTPUT:-build}"

# cd to /$OUTPUT, creating it if it doesn't exist.
cd "$(dirname "$0")"
ROOT="$(pwd)"

mkdir -p "$OUTPUT"
cd "$OUTPUT"

echo "CMake:"
echo "Output directory: $OUTPUT"
echo "Build type: $BUILD_TYPE"
if [ "$BUILD_TESTS" ]; then
    echo "Tests enabled"
    CZ_BUILD_TESTS="-DCZ_BUILD_TESTS=1"
else
    echo "Tests disabled"
    CZ_BUILD_TESTS=""
fi
cmake "$ROOT" -DCMAKE_BUILD_TYPE="$BUILD_TYPE" $CZ_BUILD_TESTS

echo
echo "Make:"
make -k
